# Name of your GitHub Actions workflow
name: Generate and Deploy RSS Link Feed

# Controls when the action will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

# Sets permissions for the workflow
permissions:
  contents: write
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run link extractor script
        run: python link_extractor.py
        env:
          SOURCE_RSS_URL: ${{ secrets.KTN_RSS_URL }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit and push if changed
        run: |
          git add links_feed.xml
          git diff --staged --quiet || (git commit -m "Update links_feed.xml" && git push)

      # --- START OF FIX ---

      # NEW STEP: Create a directory and move the generated file into it.
      # The directory name can be anything, but `_site` or `public` are common conventions.
      - name: Prepare artifact for deployment
        run: |
          mkdir -p _site
          mv links_feed.xml _site/

      # MODIFIED STEP: The 'path' now points to the directory, not the file.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      # --- END OF FIX ---

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
